### ISSUE TITLE
Add an option of a (click) handler when clicking the ellipsis

### ISSUE THREAD

**Issue by razfazz** [lentschi/ngx-ellipsis#12]
Many thanks for this great library.
This is a suggestion for a new feature.
Add an option of a (click) handler when clicking the ellipsis would be very useful. 
Someone would have the possibility to display a dialog with the whole text then.

**Comment by lentschi** [comment]
Hi!

Thanks for your feedback!
Well, you can already use (ellipsis-click-more).
But I guess, what you want is to be able to click anywhere on the text (not on some link at the end) and get some reaction...?
If so, did you try just adding (click) on a surrounding div? Then you could just toggle the contents to be something using ellipsis or an element containing the complete text.


Am 5. November 2018 15:25:07 MEZ schrieb smedasn <notifications@github.com>:

**Comment by razfazz** [comment]
thx you, it was my fault
