### ISSUE TITLE
Full text flashes on load

### ISSUE THREAD

**Issue by OxBellows** [lentschi/ngx-ellipsis#16]
When I load my component with the default ellipsis-resize-detection, the full text flashes on screen for a moment before being properly truncated. If I set ellipsis-resize-detection to window, the full text does not flash. I'd like to keep the default ellipsis-resize-detection but not have the text flash. This is happening in Chrome.

Everything else works as expected.

Thanks guys. Happy to provide any info.

**Comment by lentschi** [comment]
@OxBellows Thanks for the hint - this is fixed in `ngx-ellipsis@2.0.3`.
