### ISSUE TITLE
Ability to customize the position of clickable link and link text

### ISSUE THREAD

**Issue by ahnpnl** [lentschi/ngx-ellipsis#19]
Hi,

Thank you for a great library. I have a situation like below
![image](https://user-images.githubusercontent.com/27772165/61174714-3f7eb980-a5a4-11e9-8588-26a60747d8f8.png)

In this picture, the clickable link is customized and not on the same line as ellipsis text. The current `ellipsis-click-more` can't help me to achieve this. 

Are there any ways to make the clickable link customized ?, for example I want to customize my own link text and the link position.

**Comment by lentschi** [comment]
@ahnpnl `ellipsis-click-more` is just required if you do want the more anchor at the end of the ellipsis text. If you don't want that, just create your own clickable element, that toggles the ellipsis element's styles - for example:

```typescript
import {Component} from '@angular/core';

/** @title Virtual scroll context variables */
@Component({
  selector: 'ellipsis-example',
  styles: [`
    .mytext {
      border: 1px solid red;
      width: 180px;
    }

    .ellipsis-test {
      height: 40px;
      overflow: hidden;
    }
  `],
  template: `
    <div class="mytext" [class.ellipsis-test]="showAsEllipsis" ellipsis>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 
        sed diam nonumy eirmod tempor invidunt ut labore et 
        dolore magna aliquyam erat, sed diam voluptua.
    </div>
    <button (click)="showAsEllipsis=!showAsEllipsis">Toggle</button>
  `,
})
export class EllipsisExample {
  showAsEllipsis = true;
}
```

see working StackBlitz sample: https://stackblitz.com/edit/angular-1smu3f-rrrhgx?file=app%2Fellipsis-example.ts
