### ISSUE TITLE
Doesnt work on Angular8

### ISSUE THREAD

**Issue by gotwig** [lentschi/ngx-ellipsis#20]
I tried to use the following code in the latest angular release, but nothing is happening. 

The text is not shortened, theres no overflow hidden or anything like that, and when I use overflow hidden inside the style attribute there are no ellipsis characters (..)

`            <p style="width: 100px; height: 100px;" ellipsis
               [ellipsis-content]="variableName">
            </p>`

using div instead of p doesnt change anything.

Btw for the demo you should suggest to use P instead of DIV - DIV is a container format, P is for paragraphs.

Even better: Make a working stackblitz for the demo to prove that its working! 

Thanks for your affords! 

Cheers, Eddy

**Comment by lentschi** [comment]
@gotwig There you go: https://stackblitz.com/edit/angular-1smu3f-hp6qqa?file=package.json

**Comment by gotwig** [comment]
thx i will try it next week (Y)

**Comment by gotwig** [comment]
Im not sure why, but in my case the "..." and the text shorting only happens after I manualy change the height for example in css in the browser. When the page inititaly loads theres no ellipsis... any idea?

btw: I dont think its good practise to close tickets directly without getting feedback from the one reporting the issue.

Thank you!
