### ISSUE TITLE
Expose resize event

### ISSUE THREAD

**Issue by ahnpnl** [lentschi/ngx-ellipsis#23]
Hi,

Is it possible to expose an event emitter which emits value whenever element-resize-detector triggers ? 

I have a use case that I need to listen to the element resizing event to toggle hide/show a link "Show More". This link is hidden when the text isn't in ellipsified and this link is shown when the text is ellipsified. 

Since `ngx-ellipsis` has event listener for element resize, I think maybe there is a possibility to have an event emitter for element resizing for the directive ?

**Comment by lentschi** [comment]
@ahnpnl That was a feature that was definitely missing, I wonder why no one has asked for it so far :blush: Thanks for bringing it up!

I added it in version 2.0.5 - See the README's comments on `ellipsis-change`.
Also I created a StackBlitz to demonstrate how it works here: https://stackblitz.com/edit/angular-1smu3f-u5v7yt?file=app%2Fellipsis-example.ts

**Comment by ahnpnl** [comment]
Thank you so much, this feature helps me a lot 🎉
