### ISSUE TITLE
Content is not displayed if it's equal to 0.

### ISSUE THREAD

**Issue by alifshits** [lentschi/ngx-ellipsis#26]
Hello!

If you bind **ellipsis-content** to an integer property which has value equal to **0**, it won't be displayed.
Here is a stackblitz reproducing it: https://stackblitz.com/edit/angular-1smu3f-znwynp?file=app/ellipsis-example.ts

I believe the issue is here: https://github.com/lentschi/ngx-ellipsis/blob/4dd031c61a6ceb1c263e4f96b665eabb4062af93/projects/ngx-ellipsis/src/lib/directives/ellipsis.directive.ts#L178
if (0) -> false

The issue wouldn't happen if ellipsis directive made unconditional toString call for ellipsisContent property.

What do you think?

Thanks.

**Comment by lentschi** [comment]
@Alexander8 You're right - thanks for reporting this in such detail!

Fixed in `ngx-ellipsis@2.0.7`.

**Comment by alifshits** [comment]
Thank you, @lentschi!
