### ISSUE TITLE
Not working on angular 5.2

### ISSUE THREAD

**Issue by tonysamperi** [lentschi/ngx-ellipsis#3]
I used this:

`<span ellipsis class="sfc-as-desc">{{account.serviceDescription}}</span>`

But nothing happens

Env:
- Asus ROG 2015 (i7 6700 HQ + GTX960M + 16GB RAM DDR4)
- Chrome 65.0.3325.181 x64

<pre><code>
@angular/cdk: 5.2.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
</code></pre>

**Comment by lentschi** [comment]
@tonysamperi The ellipsis will only be applied if the content's flow is obstructed by another element or this elements size styles. Have you tried something like

```angular2html
<span ellipsis style="width:100px; height:100px;" class="sfc-as-desc">{{account.serviceDescription}}</span>
```
Also, in case `account.serviceDescription` is subject to changes, you will have to use this instead:

```angular2html
<span ellipsis style="width:100px; height:100px;" class="sfc-as-desc" [ellipsis-content]="account.serviceDescription"></span>
```

Let me know if this works for you!

**Comment by tonysamperi** [comment]
It doesn't make any sense to have a directive for the ellipsis, if I have to manually set widths for elements.
The problem for me was that the CSS ellipsis requires the container's width to be set, in order to work.

Anyway I'll close this, although it could be more useful to have something like this

[jQuery ellipsis](https://codepen.io/jjenzz/pen/liAfz)

**Comment by lentschi** [comment]
@tonysamperi 
1. It does _not_ require the element's width to be set. The affected element's dimensions just needs to be restricted in _some_ way. The most common us case being, that you have a fixed element height, and the width is 100% (i.e. determined by the surrounding container's or the client's width) - As far as I can see that should work with ngx-ellipsis!
2. jQuery ellipsis is great! But it's not an angular directive. And also, even in the codepen page you linked, they are using a fixed width too (see `.box--fixed { width: 130px;}` in the CSS section).

**Comment by tonysamperi** [comment]
1) The original CSS ellipsis requires the width to be set in order to work. Anyway a directive is useless even if it's the height to be set.
2) .box--fixed is just for some exmaples. There is also the .box--responsive which is fully working without any "restriction"

3) I added an example where the "restriction" is in the parent. Still working.
https://codepen.io/tonysamperi/pen/rdXjKV

**Comment by lentschi** [comment]
@tonysamperi  You mean the `box-custom` sample? That should also work with ngx-ellipsis (When applying it to the inner span). If it isn't, maybe there is some error in the way you import it...?

I added an example branch in my test project for you to try out (If you're still interested that is):

```bash
cd /tmp
git clone https://github.com/lentschi/ngx-ellipsis-angular5-demo.git
cd ngx-ellipsis-angular5-demo
git checkout tonysamperi
npm install
./node_modules/.bin/ng serve
```

-> Visit `localhost:4200`

For a responsive sample (where you can even resize the box using the mouse without having to resize the window) -> `checkout master` instead.

**Comment by tonysamperi** [comment]
Cool. Yes I'm interested.
Trying right now.
Thanks

**Comment by tonysamperi** [comment]
Whatever I do, it doesn't work.
I made this, but there's an error, maybe you want to fix that:
https://stackblitz.com/edit/angular-ngx-ellipsis?file=main.ts
anyway in app.component you'll se I've added a couple divs and a span...
the ellipsis doesn't work...even after I set height, width, overflow, white-space on the inner span...
