### ISSUE TITLE
emoji doesn't get truncated properly

### ISSUE THREAD

**Issue by PoiScript** [lentschi/ngx-ellipsis#35]
<img width="1029" alt="Screen Shot 2020-05-07 at 12 32 15 AM" src="https://user-images.githubusercontent.com/17513314/81203173-3579eb80-8ffa-11ea-83bf-43e339dfbf14.png">

**Comment by lentschi** [comment]
@PoiScript That is tricky and I probably won't include this in the library itself as it would become to bloated (Either I'd need to add a dependency to a lib like [runes](https://www.npmjs.com/package/runes), or I'd have to duplicate the logic in `ngx-ellipsis`, which would be event uglier).

What I will consider though, is adding a new `@Input` that let's you override the way characters are separated (Currently hardcoded in `EllipsisDirective.getTruncatedText`). This would allow you to use some other lib's function for splitting. (After all, someone might even want to prevent other characters from being split - such as `:-)` not being transformed to `:-...`)

**Until I have implemented this:** Could it be an option for you to just use `ellipsis-word-boundaries=" \n"` to only allow splitting at spaces and newlines? (That should already work in the current version)

**Comment by PoiScript** [comment]
In fact, I've checked [runes](https://github.com/dotcypress/runes/blob/develop/index.js) you mentioned above and it just contains about one hundred lines of code which is only 1.4 KB after minified and 685B plus gzipped (according to bundlephobia). I think it's totally acceptable for bundling.

**Comment by lentschi** [comment]
@PoiScript 

> ... I think it's totally acceptable for bundling.

It's not about bundling size, but about adding another dependency. This would make maintaining ngx-ellipsis more difficult (I'd need to check for upgrades to `runes` on a regular basis.)
Also, I think making this an optional input allows users more flexibility. (What if, they want to use some other lib than `runes`?)
Then there's also the performance angle: The native `String#substr` will always be faster than that of any lib. So some users might decide to just strip any emojis from the ellipsis text before and then not use `runes`.

So in `ngx-ellipsis@2.3.0` I've added an input called `[ellipsis-substr-fn]` that allows passing a custom `substr` function. See the modified [README](https://github.com/lentschi/ngx-ellipsis/blob/1e06dff8a328a0a3bcd0d88a40a4ffeffa6ecfba/README.md) and this [StackBlitz sample](https://stackblitz.com/edit/ngx-ellipsis-with-runes?file=src%2Fapp%2Fapp.component.html), which produces the following output:

![grafik](https://user-images.githubusercontent.com/783944/81473268-86a5fd00-91fd-11ea-8de3-d08be9eaa620.png)

**Comment by PoiScript** [comment]
Thanks for the explanation!
