### ISSUE TITLE
Upgrade from RxJS5 to RxJS 6

### ISSUE THREAD

**Issue by DanniB** [lentschi/ngx-ellipsis#4]
Upgrade from RxJS5 to RxJS 6. After migration without rxjs-compat, the application build fails.

`ERROR in ./node_modules/ngx-ellipsis/node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '../node_modules/ngx-ellipsis/node_modules/@angular/core/esm5'
'../src/app'
ERROR in ./node_modules/ngx-ellipsis/node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '../node_modules/ngx-ellipsis/node_modules/@angular/core/esm5'
ERROR in ./node_modules/ngx-ellipsis/node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/Subscription' in '../node_modules/ngx-ellipsis/node_modules/@angular/core/esm5'
ERROR in ./node_modules/ngx-ellipsis/node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in '../node_modules/ngx-ellipsis/node_modules/@angular/core/esm5'
ERROR in ./node_modules/ngx-ellipsis/node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/operator/share' in '../node_modules/ngx-ellipsis/node_modules/@angular/core/esm5'
`

**Comment by lentschi** [comment]
@DanniB Thanks for reporting this bug and sorry that it took me so long to respond.
The library bundler I used for angular 4 apparently had compatibility issues with rxjs 6. I upgraded to angular 6 with its built-in library bundler and this seems to be resolved.
