### ISSUE TITLE
ellipsis value not working with component variable

### ISSUE THREAD

**Issue by Knochenmark** [lentschi/ngx-ellipsis#44]
Hi, I would like to pass the ellipsis prop a combined string with a component variable or alternatively use a getter function for the string so I can change it on the fly instead of a static `"...more"` or alike.

It seems like the prop doesn't accept anything else than a static string though.

My intention is, I would like to use the cut-off string to determine how much items were cutoff and use it as a count and pass it back into the ellipsis prop. So I get something along the lines of `... (2)more`

Unfortunately the ellipsis prop fails for concatinated strings, functions, member variables etc.

Could you elaborate if this is supported or not? The typings are indicating it should work though.

If it should work, a small example would be great! Thanks 👍

**Comment by lentschi** [comment]
Yes, this is a bug I can confirm. I'll look into it asap.
The following works:
https://stackblitz.com/edit/ngx-ellipsis-change-hx79pb?file=src/app/app.component.ts

... but as soon as you use the `(ellipsis-click-more)`, it will no longer auto-update. 

(Until I fix this, you could try and manually workaround by using `#ell="ellipsis"` in the template and `this.ell.applyEllipsis()` in the component code whenever `(ellipsis-change)` is emitted.)

**Comment by Knochenmark** [comment]
@lentschi Ah thanks for the clarification. Yeah, I'm using the click-more didn't realise that this could be the culprit :)

The way it works already is pretty good, the cut-off number would be more like the cherry on the top.
So no pressure, take your time. 👍

**Comment by lentschi** [comment]
Fixed in `ngx-ellipsis@2.3.2`
