### ISSUE TITLE
tslib warning when installing deps

### ISSUE THREAD

**Issue by ahnpnl** [lentschi/ngx-ellipsis#46]
Hi,

I am using Angular 10 and it shows warning about `tslib` when installing `ngx-ellipsis`.

```
warning " > ngx-ellipsis@3.0.0" has incorrect peer dependency "tslib@^1.10.0".
```

Would you please check and fix it ?

**Comment by lentschi** [comment]
@ahnpnl Yes, thanks for bringing this up - This should be fixed (along with #47) in `ngx-ellipsis@3.1.0`.
