### ISSUE TITLE
Issue with (ellipsis-click-more)

### ISSUE THREAD

**Issue by Devyani20** [lentschi/ngx-ellipsis#51]
Is there a way to get ellipsis non -clickable (in black color) along with the text that is give against ellipsis

 <div  ellipsis =" ...Show more"
            [ellipsis-content]="guidelines"
            (ellipsis-click-more)="showEllipsis = false"
            class="sample white-space"></div>
        </div>
The issue is that when i use ellipsis -click-more it coverts the ellipsis also to clickable form but i donot need them to be in clickable form rather needs the text Show more only clickable and if i remove(...)  that have been given along with show more text the ellipsis(...) get truncated

**Comment by lentschi** [comment]
I'm sorry - I'm not quite sure, what you mean...? :thinking:  Could you maybe provide a sample/mockup?

**Comment by Devyani20** [comment]
yes sure 
![image](https://user-images.githubusercontent.com/57898970/107746386-c45f2580-6d3b-11eb-9e9a-d62170a0ba96.png)
so in this image you can see that i get the ellipsis also in a link form which i donot need 
i need the ellipsis in non clickable form that is in black color
like this

![image](https://user-images.githubusercontent.com/57898970/107746591-1902a080-6d3c-11eb-97fb-962716ce31cd.png)

**Comment by lentschi** [comment]
Ah, now I get it :slightly_smiling_face: 

`ngx-ellipsis` currently has no programmatic way to do that, but you could just use CSS like this:

```css
.ngx-ellipsis-more {
  display: inline-block;
}

.ngx-ellipsis-more::before {
  padding-right: 3px;
  content: '...';
  display: inline-block;
}
```
( see [this StackBlitz](https://stackblitz.com/edit/ngx-ellipsis-separated-anchor?file=src/app/app.component.css) )

Unfortunately this still leaves the dots clickable even if they're no longer _displayed_ as a link - but is that really an issue for you?
If yes, you might find a CSS that does that too (Though I'm not sure, if that's possible).

Or you could try out ngx-ellipsis' sister project [ngx-nested-ellipsis](https://github.com/lentschi/ngx-nested-ellipsis) which supports html contents for both contents and the ellipsis indicator as it's called there ( search for [indicator in this StackBlitz sample](https://stackblitz.com/github/lentschi/ngx-nested-ellipsis?file=src%2Fapp%2Fapp.component.html) ).

**Comment by Devyani20** [comment]
Okay Thank you for such a quick response
