### ISSUE TITLE
Not able to use library in ie 11

### ISSUE THREAD

**Issue by Devyani20** [lentschi/ngx-ellipsis#53]
The issue is  that the library is not working in ie11 and giving this error
![image](https://user-images.githubusercontent.com/57898970/114677319-cfc4d200-9d27-11eb-9507-3c0cb7d7d4be.png)
This is because of this .browserslistrc file as it excludes the ie11 version
Can you provide a way to make it work in ie 11 also

**Comment by lentschi** [comment]
I'm not sure - I'd have to check, probably using some prior version of ngx-ellipsis could solve your problem 🤔 
But before I do: Are you aware of https://death-to-ie11.com/?

**Comment by Devyani20** [comment]
Yes I am aware of the ie part but can you provide the support optionally so that if somebody needs can use it.
and there was a bug fix in v1.1.1 which I need
so can you pls look into it

**Comment by lentschi** [comment]
Fixed in `ngx-ellipsis@3.1.2`- However I'll stop supporting IE as soon as angular 13 is stable as it will no longer be supported by the framework then - see: https://angular.io/guide/deprecations#internet-explorer-11

**Comment by lentschi** [comment]
> However I'll stop supporting IE as soon as angular 13 is stable

It has been done - see https://github.com/lentschi/ngx-ellipsis/commit/035613fe3a87422d69f826abfb5f2245a5abb9e1
IE11 is no longer supported since `ngx-ellipsis@4.0.0`
