### ISSUE TITLE
unable to utilize [ellipsis-content]

### ISSUE THREAD

**Issue by herin0506** [lentschi/ngx-ellipsis#6]
I am unable to utilize [ellipsis-content]. Below is my html
"<p class="abc" [ellipsis-content]="object['key1']">{{ object['key1'] }}

"
I want to change the content

element on clicking the list which i have rendered on screen from some other component on same page. The input for this component is the object containing all the details of single (one which is clicked from list) item of list.

I get below error in console of browser:
"Template parse errors:
Can't bind to 'ellipsis-content' since it isn't a known property of 'p'."

Only "ellipsis" is consumable. And when "ellipsis" is used then on change of content, the change do not reflect on screen (may be it requires reloading of component and its DOM).
Please help with the syntax or any example which consumes [ellipsis-content] for dynamic content.

**Comment by lentschi** [comment]
@herinlakdawala Are you sure you followed the `README` and added the import of `EllipsisModule` to your app module? (Else, depending on your configuration, this might fail silently.)
If so, `<p class="abc" ellipsis  [ellipsis-content]="object['key1']"></p>` should fulfill your needs. (Don't add it as a text node too)

**Comment by herin0506** [comment]
@lentschi Thanks for your prompt response. I was using either "ellipsis" or  "[ellipsis-content]" and the fact is both need to be used at same time. 
It would be helpful if you update the README with the full example like "<p class="abc" ellipsis [ellipsis-content]="object['key1']"></p>" which will help others like me.
Thanks again. :)

**Comment by lentschi** [comment]
@herinlakdawala Yeah, you're right - I should add that. Also I'm planning to do a demo app, when I find the time...
