### ISSUE TITLE
Nr. of lines option?

### ISSUE THREAD

**Issue by casni14** [lentschi/ngx-ellipsis#7]
Is it possible to set a fixed number of lines e.g. 2?
I can't seem to find it in the readme

**Comment by lentschi** [comment]
@casni14 No sorry, there is no specific setting for that.
However you can easily achieve this by limiting the container's `width` and `height` using css. How many lines of text will fit in it is determined by `line-height` (and `padding` if any).

**Comment by casni14** [comment]
Ahh nice, thank you for the quick response :) 
Maybe you should add that in the readme?
