### ISSUE TITLE
Ellipsis on new line.

### ISSUE THREAD

**Issue by Mendzyy** [lentschi/ngx-ellipsis#93]
This is more of a question.

Is it somehow possible to have ellipsis on a new line? without see more link.

**Comment by lentschi** [comment]
Hi @Mendzyy 
Not quite sure, what you mean - like this...?:
![grafik](https://github.com/lentschi/ngx-ellipsis/assets/783944/4598524c-a507-4ecc-bc85-245f8d35d091)
If so, you could set an empty string as `ellipsis` and display the contents using the `::after` css selector, if  `(ellipsis-change)` emitted a number (meaning the text had been truncated at some point) - see [Stackblitz here](https://stackblitz.com/edit/github-acwka7-yf3wjc?file=src%2Fapp%2Fapp.component.css).
